api_platform:
    mapping:
        paths:
            [
                "%kernel.project_dir%/vendor/controleonline/products/src/Entity",
                "%kernel.project_dir%/vendor/controleonline/products/Resource",
            ]
    
